import AboutMe from "@/components/AboutMe";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Works from "@/components/Portfolio";
import Skills from "@/components/Skills";

import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" bg-gradient-to-r from-purple-400 to-blue-500">
        <Navbar />
        <main className="">
          <Hero />
          <AboutMe />
          <Works />
          <Skills />
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Home;
